/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Jon Snow
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        Temperature = new javax.swing.JButton();
        Precipitation = new javax.swing.JButton();
        TempPanel = new javax.swing.JPanel();
        TempPer1 = new javax.swing.JLabel();
        PeriodTempP1 = new javax.swing.JButton();
        TempP2Period1 = new javax.swing.JButton();
        TempBack1 = new javax.swing.JButton();
        TempP1Label1 = new javax.swing.JLabel();
        SeasonTempP2 = new javax.swing.JButton();
        TempAnnualP2 = new javax.swing.JButton();
        TempLabelP3 = new javax.swing.JLabel();
        SeasonalPrecP3 = new javax.swing.JButton();
        AnnualPrecP3 = new javax.swing.JButton();
        PrecPanel = new javax.swing.JPanel();
        PrePer = new javax.swing.JLabel();
        PeriodPrecP1 = new javax.swing.JButton();
        PrecP2Period = new javax.swing.JButton();
        PrecBack = new javax.swing.JButton();
        PrecP1Label = new javax.swing.JLabel();
        SeasonPrecP1 = new javax.swing.JButton();
        precAnnualP1 = new javax.swing.JButton();
        PrecLabelP2 = new javax.swing.JLabel();
        SeasonalPrecP2 = new javax.swing.JButton();
        AnnualPrecP2 = new javax.swing.JButton();
        ProgressBarTempP1P = new javax.swing.JPanel();
        javax.swing.JProgressBar jProgressBar1 = new javax.swing.JProgressBar();
        BackFromPBar = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        ProgressBarTempP1P2 = new javax.swing.JPanel();
        jProgressBar2 = new javax.swing.JProgressBar();
        BackFromPBar1 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        ProgressBarPrecP1P3 = new javax.swing.JPanel();
        jProgressBar3 = new javax.swing.JProgressBar();
        BackFromPBar2 = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        ProgressBarPrecP1P9 = new javax.swing.JPanel();
        javax.swing.JProgressBar jProgressBar14 = new javax.swing.JProgressBar();
        BackFromPBar13 = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        SeasonalTempP1 = new javax.swing.JPanel();
        javax.swing.JProgressBar SummerT1 = new javax.swing.JProgressBar();
        BackFromPBar14 = new javax.swing.JButton();
        javax.swing.JProgressBar WinterT1 = new javax.swing.JProgressBar();
        javax.swing.JProgressBar FallT1 = new javax.swing.JProgressBar();
        javax.swing.JProgressBar SpringT1 = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        SeasonalTempP2 = new javax.swing.JPanel();
        javax.swing.JProgressBar SummerT2 = new javax.swing.JProgressBar();
        BackFromPBar15 = new javax.swing.JButton();
        javax.swing.JProgressBar WinterT2 = new javax.swing.JProgressBar();
        javax.swing.JProgressBar FallT2 = new javax.swing.JProgressBar();
        javax.swing.JProgressBar SpringT2 = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        SeasonalPrecP1 = new javax.swing.JPanel();
        javax.swing.JProgressBar SummerT6 = new javax.swing.JProgressBar();
        BackFromPBar19 = new javax.swing.JButton();
        javax.swing.JProgressBar WinterT6 = new javax.swing.JProgressBar();
        javax.swing.JProgressBar FallT6 = new javax.swing.JProgressBar();
        javax.swing.JProgressBar SpringT6 = new javax.swing.JProgressBar();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        SeasonalPrecP9 = new javax.swing.JPanel();
        javax.swing.JProgressBar SummerT7 = new javax.swing.JProgressBar();
        BackFromPBar20 = new javax.swing.JButton();
        javax.swing.JProgressBar WinterT7 = new javax.swing.JProgressBar();
        javax.swing.JProgressBar FallT7 = new javax.swing.JProgressBar();
        javax.swing.JProgressBar SpringT7 = new javax.swing.JProgressBar();
        jLabel7 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        TempP1 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        TempP2 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        PRecP1 = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        PrecP2 = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MainMenu = new javax.swing.JMenu();
        ExitMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Temperature.setText("Temperature");
        Temperature.setMaximumSize(new java.awt.Dimension(200, 35));
        Temperature.setMinimumSize(new java.awt.Dimension(200, 35));
        Temperature.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TemperatureActionPerformed(evt);
            }
        });

        Precipitation.setText("Precipitation");
        Precipitation.setMaximumSize(new java.awt.Dimension(200, 35));
        Precipitation.setMinimumSize(new java.awt.Dimension(200, 35));
        Precipitation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrecipitationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(231, 231, 231)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Precipitation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Temperature, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE))
                .addContainerGap(772, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(Temperature, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102)
                .addComponent(Precipitation, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(390, Short.MAX_VALUE))
        );

        TempPer1.setText("Period Temperature");

        PeriodTempP1.setText("Periods");
        PeriodTempP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PeriodTempP1ActionPerformed(evt);
            }
        });

        TempP2Period1.setText("Periods");
        TempP2Period1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TempP2Period1ActionPerformed(evt);
            }
        });

        TempBack1.setText("Back");
        TempBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TempBack1ActionPerformed(evt);
            }
        });

        TempP1Label1.setText("1986 - 2005");

        SeasonTempP2.setText("Seasonal");
        SeasonTempP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeasonTempP2ActionPerformed(evt);
            }
        });

        TempAnnualP2.setText("Annual ");
        TempAnnualP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TempAnnualP2ActionPerformed(evt);
            }
        });

        TempLabelP3.setText("2040 - 2069");

        SeasonalPrecP3.setText("Seasonal");
        SeasonalPrecP3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeasonalPrecP3ActionPerformed(evt);
            }
        });

        AnnualPrecP3.setText("Annual");
        AnnualPrecP3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnnualPrecP3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TempPanelLayout = new javax.swing.GroupLayout(TempPanel);
        TempPanel.setLayout(TempPanelLayout);
        TempPanelLayout.setHorizontalGroup(
            TempPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TempPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(TempBack1)
                .addGap(107, 107, 107))
            .addGroup(TempPanelLayout.createSequentialGroup()
                .addGroup(TempPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TempPanelLayout.createSequentialGroup()
                        .addGap(344, 344, 344)
                        .addGroup(TempPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TempP2Period1)
                            .addComponent(PeriodTempP1)
                            .addComponent(SeasonTempP2)
                            .addComponent(TempAnnualP2)
                            .addComponent(TempLabelP3)
                            .addComponent(SeasonalPrecP3)
                            .addComponent(AnnualPrecP3)))
                    .addGroup(TempPanelLayout.createSequentialGroup()
                        .addGap(356, 356, 356)
                        .addComponent(TempP1Label1))
                    .addGroup(TempPanelLayout.createSequentialGroup()
                        .addGap(321, 321, 321)
                        .addComponent(TempPer1)))
                .addContainerGap(985, Short.MAX_VALUE))
        );
        TempPanelLayout.setVerticalGroup(
            TempPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TempPanelLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(TempPer1)
                .addGap(70, 70, 70)
                .addComponent(TempP1Label1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PeriodTempP1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SeasonTempP2)
                .addGap(18, 18, 18)
                .addComponent(TempAnnualP2)
                .addGap(56, 56, 56)
                .addComponent(TempLabelP3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TempP2Period1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SeasonalPrecP3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AnnualPrecP3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 305, Short.MAX_VALUE)
                .addComponent(TempBack1)
                .addGap(78, 78, 78))
        );

        PrePer.setText("Period Precipitation");

        PeriodPrecP1.setText("Periods");
        PeriodPrecP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PeriodPrecP1ActionPerformed(evt);
            }
        });

        PrecP2Period.setText("Periods");
        PrecP2Period.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrecP2PeriodActionPerformed(evt);
            }
        });

        PrecBack.setText("Back");
        PrecBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrecBackActionPerformed(evt);
            }
        });

        PrecP1Label.setText("1986 - 2005");

        SeasonPrecP1.setText("Seasonal");
        SeasonPrecP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeasonPrecP1ActionPerformed(evt);
            }
        });

        precAnnualP1.setText("Annual ");
        precAnnualP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precAnnualP1ActionPerformed(evt);
            }
        });

        PrecLabelP2.setText("2040 - 2069");

        SeasonalPrecP2.setText("Seasonal");
        SeasonalPrecP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeasonalPrecP2ActionPerformed(evt);
            }
        });

        AnnualPrecP2.setText("Annual");
        AnnualPrecP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnnualPrecP2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PrecPanelLayout = new javax.swing.GroupLayout(PrecPanel);
        PrecPanel.setLayout(PrecPanelLayout);
        PrecPanelLayout.setHorizontalGroup(
            PrecPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PrecPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(PrecBack)
                .addGap(107, 107, 107))
            .addGroup(PrecPanelLayout.createSequentialGroup()
                .addGroup(PrecPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PrecPanelLayout.createSequentialGroup()
                        .addGap(344, 344, 344)
                        .addGroup(PrecPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PrecP2Period)
                            .addComponent(PeriodPrecP1)
                            .addComponent(SeasonPrecP1)
                            .addComponent(precAnnualP1)
                            .addComponent(PrecLabelP2)
                            .addComponent(SeasonalPrecP2)
                            .addComponent(AnnualPrecP2)))
                    .addGroup(PrecPanelLayout.createSequentialGroup()
                        .addGap(356, 356, 356)
                        .addComponent(PrecP1Label))
                    .addGroup(PrecPanelLayout.createSequentialGroup()
                        .addGap(321, 321, 321)
                        .addComponent(PrePer)))
                .addContainerGap(990, Short.MAX_VALUE))
        );
        PrecPanelLayout.setVerticalGroup(
            PrecPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PrecPanelLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(PrePer)
                .addGap(70, 70, 70)
                .addComponent(PrecP1Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PeriodPrecP1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SeasonPrecP1)
                .addGap(18, 18, 18)
                .addComponent(precAnnualP1)
                .addGap(52, 52, 52)
                .addComponent(PrecLabelP2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PrecP2Period)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SeasonalPrecP2)
                .addGap(18, 18, 18)
                .addComponent(AnnualPrecP2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 312, Short.MAX_VALUE)
                .addComponent(PrecBack)
                .addGap(78, 78, 78))
        );

        jProgressBar1.setMaximum(45);
        jProgressBar1.setMinimum(-25);
        jProgressBar1.setOrientation(1);
        jProgressBar1.setValue(10);
        jProgressBar1.setFocusTraversalPolicyProvider(true);

        BackFromPBar.setText("Back");
        BackFromPBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackFromPBarActionPerformed(evt);
            }
        });

        jLabel12.setText("Minimum = -25.38");

        jLabel17.setText("Median = 9.831");

        jLabel22.setText("Max = 45.40");

        javax.swing.GroupLayout ProgressBarTempP1PLayout = new javax.swing.GroupLayout(ProgressBarTempP1P);
        ProgressBarTempP1P.setLayout(ProgressBarTempP1PLayout);
        ProgressBarTempP1PLayout.setHorizontalGroup(
            ProgressBarTempP1PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProgressBarTempP1PLayout.createSequentialGroup()
                .addGap(355, 355, 355)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addGroup(ProgressBarTempP1PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel17)
                    .addComponent(jLabel22))
                .addContainerGap(757, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProgressBarTempP1PLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BackFromPBar)
                .addGap(89, 89, 89))
        );
        ProgressBarTempP1PLayout.setVerticalGroup(
            ProgressBarTempP1PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProgressBarTempP1PLayout.createSequentialGroup()
                .addGap(199, 199, 199)
                .addGroup(ProgressBarTempP1PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ProgressBarTempP1PLayout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel17)
                        .addGap(97, 97, 97)
                        .addComponent(jLabel12)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 368, Short.MAX_VALUE)
                .addComponent(BackFromPBar)
                .addGap(84, 84, 84))
        );

        jProgressBar2.setMaximum(50);
        jProgressBar2.setMinimum(-20);
        jProgressBar2.setOrientation(1);
        jProgressBar2.setValue(13);
        jProgressBar2.setFocusTraversalPolicyProvider(true);

        BackFromPBar1.setText("Back");
        BackFromPBar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackFromPBar1ActionPerformed(evt);
            }
        });

        jLabel27.setText("Min: -20.1");

        jLabel28.setText("Max: 50.25");

        jLabel29.setText("Median: 12.574");

        javax.swing.GroupLayout ProgressBarTempP1P2Layout = new javax.swing.GroupLayout(ProgressBarTempP1P2);
        ProgressBarTempP1P2.setLayout(ProgressBarTempP1P2Layout);
        ProgressBarTempP1P2Layout.setHorizontalGroup(
            ProgressBarTempP1P2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProgressBarTempP1P2Layout.createSequentialGroup()
                .addGap(355, 355, 355)
                .addComponent(jProgressBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88)
                .addGroup(ProgressBarTempP1P2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27)
                    .addComponent(jLabel28)
                    .addComponent(jLabel29))
                .addContainerGap(774, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProgressBarTempP1P2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BackFromPBar1)
                .addGap(89, 89, 89))
        );
        ProgressBarTempP1P2Layout.setVerticalGroup(
            ProgressBarTempP1P2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProgressBarTempP1P2Layout.createSequentialGroup()
                .addGap(199, 199, 199)
                .addGroup(ProgressBarTempP1P2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jProgressBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ProgressBarTempP1P2Layout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel29)
                        .addGap(97, 97, 97)
                        .addComponent(jLabel27)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 368, Short.MAX_VALUE)
                .addComponent(BackFromPBar1)
                .addGap(84, 84, 84))
        );

        jProgressBar3.setMaximum(198);
        jProgressBar3.setOrientation(1);
        jProgressBar3.setValue(8);
        jProgressBar3.setFocusTraversalPolicyProvider(true);

        BackFromPBar2.setText("Back");
        BackFromPBar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackFromPBar2ActionPerformed(evt);
            }
        });

        jLabel30.setText("Min: 0.0 mm/day");

        jLabel31.setText("Max: 198.06");

        jLabel32.setText("Median: 0.5354 mm/day");

        javax.swing.GroupLayout ProgressBarPrecP1P3Layout = new javax.swing.GroupLayout(ProgressBarPrecP1P3);
        ProgressBarPrecP1P3.setLayout(ProgressBarPrecP1P3Layout);
        ProgressBarPrecP1P3Layout.setHorizontalGroup(
            ProgressBarPrecP1P3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProgressBarPrecP1P3Layout.createSequentialGroup()
                .addGap(355, 355, 355)
                .addComponent(jProgressBar3, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122)
                .addGroup(ProgressBarPrecP1P3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel31)
                    .addComponent(jLabel30)
                    .addComponent(jLabel32))
                .addContainerGap(656, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProgressBarPrecP1P3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BackFromPBar2)
                .addGap(89, 89, 89))
        );
        ProgressBarPrecP1P3Layout.setVerticalGroup(
            ProgressBarPrecP1P3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProgressBarPrecP1P3Layout.createSequentialGroup()
                .addGap(199, 199, 199)
                .addGroup(ProgressBarPrecP1P3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jProgressBar3, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ProgressBarPrecP1P3Layout.createSequentialGroup()
                        .addComponent(jLabel31)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel32)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel30)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 368, Short.MAX_VALUE)
                .addComponent(BackFromPBar2)
                .addGap(84, 84, 84))
        );

        jProgressBar14.setMaximum(183);
        jProgressBar14.setOrientation(1);
        jProgressBar14.setValue(7);
        jProgressBar14.setFocusTraversalPolicyProvider(true);

        BackFromPBar13.setText("Back");
        BackFromPBar13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackFromPBar13ActionPerformed(evt);
            }
        });

        jLabel33.setText("Max: 183.278 mm/day");

        jLabel34.setText("Min: 0.0 mm/day");

        jLabel35.setText("Median: 0.5166 mm/day");

        javax.swing.GroupLayout ProgressBarPrecP1P9Layout = new javax.swing.GroupLayout(ProgressBarPrecP1P9);
        ProgressBarPrecP1P9.setLayout(ProgressBarPrecP1P9Layout);
        ProgressBarPrecP1P9Layout.setHorizontalGroup(
            ProgressBarPrecP1P9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProgressBarPrecP1P9Layout.createSequentialGroup()
                .addGap(355, 355, 355)
                .addComponent(jProgressBar14, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(ProgressBarPrecP1P9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProgressBarPrecP1P9Layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jLabel33))
                    .addGroup(ProgressBarPrecP1P9Layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addGroup(ProgressBarPrecP1P9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel35)
                            .addComponent(jLabel34))))
                .addContainerGap(602, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProgressBarPrecP1P9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BackFromPBar13)
                .addGap(89, 89, 89))
        );
        ProgressBarPrecP1P9Layout.setVerticalGroup(
            ProgressBarPrecP1P9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProgressBarPrecP1P9Layout.createSequentialGroup()
                .addGap(199, 199, 199)
                .addGroup(ProgressBarPrecP1P9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jProgressBar14, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ProgressBarPrecP1P9Layout.createSequentialGroup()
                        .addComponent(jLabel33)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel35)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel34)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 368, Short.MAX_VALUE)
                .addComponent(BackFromPBar13)
                .addGap(84, 84, 84))
        );

        SummerT1.setMaximum(45);
        SummerT1.setMinimum(-25);
        SummerT1.setOrientation(1);
        SummerT1.setValue(10);
        SummerT1.setFocusTraversalPolicyProvider(true);

        BackFromPBar14.setText("Back");
        BackFromPBar14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackFromPBar14ActionPerformed(evt);
            }
        });

        WinterT1.setOrientation(1);
        WinterT1.setFocusTraversalPolicyProvider(true);

        FallT1.setOrientation(1);
        FallT1.setFocusTraversalPolicyProvider(true);

        SpringT1.setOrientation(1);
        SpringT1.setFocusTraversalPolicyProvider(true);

        jLabel1.setText("Seasonal Temperature 1986-2005");

        jLabel13.setText("Summer");

        jLabel14.setText("Winter");

        jLabel15.setText("Fall");

        jLabel16.setText("Spring");

        javax.swing.GroupLayout SeasonalTempP1Layout = new javax.swing.GroupLayout(SeasonalTempP1);
        SeasonalTempP1.setLayout(SeasonalTempP1Layout);
        SeasonalTempP1Layout.setHorizontalGroup(
            SeasonalTempP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SeasonalTempP1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BackFromPBar14)
                .addGap(111, 111, 111))
            .addGroup(SeasonalTempP1Layout.createSequentialGroup()
                .addGroup(SeasonalTempP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SeasonalTempP1Layout.createSequentialGroup()
                        .addGap(399, 399, 399)
                        .addComponent(jLabel1))
                    .addGroup(SeasonalTempP1Layout.createSequentialGroup()
                        .addGroup(SeasonalTempP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(SeasonalTempP1Layout.createSequentialGroup()
                                .addGap(134, 134, 134)
                                .addComponent(SummerT1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(210, 210, 210)
                                .addComponent(WinterT1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(SeasonalTempP1Layout.createSequentialGroup()
                                .addGap(114, 114, 114)
                                .addComponent(jLabel13)
                                .addGap(148, 148, 148)
                                .addComponent(jLabel14)))
                        .addGap(198, 198, 198)
                        .addGroup(SeasonalTempP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(SeasonalTempP1Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(155, 155, 155)
                                .addComponent(jLabel16))
                            .addGroup(SeasonalTempP1Layout.createSequentialGroup()
                                .addComponent(FallT1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(190, 190, 190)
                                .addComponent(SpringT1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(179, Short.MAX_VALUE))
        );
        SeasonalTempP1Layout.setVerticalGroup(
            SeasonalTempP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SeasonalTempP1Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 305, Short.MAX_VALUE)
                .addGroup(SeasonalTempP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SummerT1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WinterT1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FallT1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SpringT1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(SeasonalTempP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addGap(232, 232, 232)
                .addComponent(BackFromPBar14)
                .addGap(48, 48, 48))
        );

        SummerT2.setOrientation(1);
        SummerT2.setFocusTraversalPolicyProvider(true);

        BackFromPBar15.setText("Back");
        BackFromPBar15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackFromPBar15ActionPerformed(evt);
            }
        });

        WinterT2.setOrientation(1);
        WinterT2.setFocusTraversalPolicyProvider(true);

        FallT2.setOrientation(1);
        FallT2.setFocusTraversalPolicyProvider(true);

        SpringT2.setOrientation(1);
        SpringT2.setFocusTraversalPolicyProvider(true);

        jLabel2.setText("Seasonal Temperature 2040 - 2069");

        jLabel18.setText("Summer");

        jLabel19.setText("Winter");

        jLabel20.setText("Fall");

        jLabel21.setText("Spring");

        javax.swing.GroupLayout SeasonalTempP2Layout = new javax.swing.GroupLayout(SeasonalTempP2);
        SeasonalTempP2.setLayout(SeasonalTempP2Layout);
        SeasonalTempP2Layout.setHorizontalGroup(
            SeasonalTempP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SeasonalTempP2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BackFromPBar15)
                .addGap(111, 111, 111))
            .addGroup(SeasonalTempP2Layout.createSequentialGroup()
                .addGroup(SeasonalTempP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SeasonalTempP2Layout.createSequentialGroup()
                        .addGap(399, 399, 399)
                        .addComponent(jLabel2))
                    .addGroup(SeasonalTempP2Layout.createSequentialGroup()
                        .addGroup(SeasonalTempP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(SeasonalTempP2Layout.createSequentialGroup()
                                .addGap(134, 134, 134)
                                .addComponent(SummerT2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(210, 210, 210)
                                .addComponent(WinterT2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(SeasonalTempP2Layout.createSequentialGroup()
                                .addGap(95, 95, 95)
                                .addComponent(jLabel18)
                                .addGap(163, 163, 163)
                                .addComponent(jLabel19)))
                        .addGap(202, 202, 202)
                        .addGroup(SeasonalTempP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(SeasonalTempP2Layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addGap(163, 163, 163)
                                .addComponent(jLabel21))
                            .addGroup(SeasonalTempP2Layout.createSequentialGroup()
                                .addComponent(FallT2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(190, 190, 190)
                                .addComponent(SpringT2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(171, Short.MAX_VALUE))
        );
        SeasonalTempP2Layout.setVerticalGroup(
            SeasonalTempP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SeasonalTempP2Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 276, Short.MAX_VALUE)
                .addGroup(SeasonalTempP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SeasonalTempP2Layout.createSequentialGroup()
                        .addGroup(SeasonalTempP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SummerT2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(WinterT2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FallT2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SpringT2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(SeasonalTempP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(SeasonalTempP2Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jLabel19))
                            .addGroup(SeasonalTempP2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(SeasonalTempP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel20))))
                        .addGap(239, 239, 239))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SeasonalTempP2Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(230, 230, 230)))
                .addComponent(BackFromPBar15)
                .addGap(48, 48, 48))
        );

        SummerT6.setOrientation(1);
        SummerT6.setFocusTraversalPolicyProvider(true);

        BackFromPBar19.setText("Back");
        BackFromPBar19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackFromPBar19ActionPerformed(evt);
            }
        });

        WinterT6.setOrientation(1);
        WinterT6.setFocusTraversalPolicyProvider(true);

        FallT6.setOrientation(1);
        FallT6.setFocusTraversalPolicyProvider(true);

        SpringT6.setOrientation(1);
        SpringT6.setFocusTraversalPolicyProvider(true);

        jLabel6.setText("Seasonal Temperature 1986 - 2005");

        jLabel8.setText("Summer");

        jLabel9.setText("Winter");

        jLabel10.setText("Fall");

        jLabel11.setText("Spring");

        javax.swing.GroupLayout SeasonalPrecP1Layout = new javax.swing.GroupLayout(SeasonalPrecP1);
        SeasonalPrecP1.setLayout(SeasonalPrecP1Layout);
        SeasonalPrecP1Layout.setHorizontalGroup(
            SeasonalPrecP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SeasonalPrecP1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BackFromPBar19)
                .addGap(111, 111, 111))
            .addGroup(SeasonalPrecP1Layout.createSequentialGroup()
                .addGroup(SeasonalPrecP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SeasonalPrecP1Layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(SummerT6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(210, 210, 210)
                        .addComponent(WinterT6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(223, 223, 223)
                        .addComponent(FallT6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(190, 190, 190)
                        .addComponent(SpringT6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(SeasonalPrecP1Layout.createSequentialGroup()
                        .addGap(399, 399, 399)
                        .addComponent(jLabel6))
                    .addGroup(SeasonalPrecP1Layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jLabel8)
                        .addGap(172, 172, 172)
                        .addComponent(jLabel9)
                        .addGap(168, 168, 168)
                        .addComponent(jLabel10)
                        .addGap(131, 131, 131)
                        .addComponent(jLabel11)))
                .addContainerGap(245, Short.MAX_VALUE))
        );
        SeasonalPrecP1Layout.setVerticalGroup(
            SeasonalPrecP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SeasonalPrecP1Layout.createSequentialGroup()
                .addGroup(SeasonalPrecP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SeasonalPrecP1Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 276, Short.MAX_VALUE)
                        .addGroup(SeasonalPrecP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SummerT6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(WinterT6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FallT6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SpringT6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55)
                        .addGroup(SeasonalPrecP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(215, 215, 215))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SeasonalPrecP1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(SeasonalPrecP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(207, 207, 207)))
                .addComponent(BackFromPBar19)
                .addGap(48, 48, 48))
        );

        SummerT7.setOrientation(1);
        SummerT7.setFocusTraversalPolicyProvider(true);

        BackFromPBar20.setText("Back");
        BackFromPBar20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackFromPBar20ActionPerformed(evt);
            }
        });

        WinterT7.setOrientation(1);
        WinterT7.setFocusTraversalPolicyProvider(true);

        FallT7.setOrientation(1);
        FallT7.setFocusTraversalPolicyProvider(true);

        SpringT7.setOrientation(1);
        SpringT7.setFocusTraversalPolicyProvider(true);

        jLabel7.setText("Seasonal Temperature 2040 - 2069");

        jLabel23.setText("Summer");

        jLabel24.setText("Winter");

        jLabel25.setText("Fall");

        jLabel26.setText("Spring");

        javax.swing.GroupLayout SeasonalPrecP9Layout = new javax.swing.GroupLayout(SeasonalPrecP9);
        SeasonalPrecP9.setLayout(SeasonalPrecP9Layout);
        SeasonalPrecP9Layout.setHorizontalGroup(
            SeasonalPrecP9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SeasonalPrecP9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BackFromPBar20)
                .addGap(111, 111, 111))
            .addGroup(SeasonalPrecP9Layout.createSequentialGroup()
                .addGroup(SeasonalPrecP9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SeasonalPrecP9Layout.createSequentialGroup()
                        .addGap(399, 399, 399)
                        .addComponent(jLabel7))
                    .addGroup(SeasonalPrecP9Layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addGroup(SeasonalPrecP9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(SeasonalPrecP9Layout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addGap(123, 123, 123)
                                .addComponent(jLabel24)
                                .addGap(183, 183, 183)
                                .addComponent(jLabel26)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel25))
                            .addGroup(SeasonalPrecP9Layout.createSequentialGroup()
                                .addComponent(SummerT7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(210, 210, 210)
                                .addComponent(WinterT7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(223, 223, 223)
                                .addComponent(FallT7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(190, 190, 190)
                                .addComponent(SpringT7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(203, Short.MAX_VALUE))
        );
        SeasonalPrecP9Layout.setVerticalGroup(
            SeasonalPrecP9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SeasonalPrecP9Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 234, Short.MAX_VALUE)
                .addGroup(SeasonalPrecP9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SummerT7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WinterT7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FallT7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SpringT7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(SeasonalPrecP9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SeasonalPrecP9Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(SeasonalPrecP9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24)
                            .addComponent(jLabel26)))
                    .addGroup(SeasonalPrecP9Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel25)))
                .addGap(241, 241, 241)
                .addComponent(BackFromPBar20)
                .addGap(48, 48, 48))
        );

        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FIRST.png"))); // NOI18N

        javax.swing.GroupLayout TempP1Layout = new javax.swing.GroupLayout(TempP1);
        TempP1.setLayout(TempP1Layout);
        TempP1Layout.setHorizontalGroup(
            TempP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TempP1Layout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addComponent(jLabel36)
                .addContainerGap(307, Short.MAX_VALUE))
        );
        TempP1Layout.setVerticalGroup(
            TempP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TempP1Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jLabel36)
                .addContainerGap(137, Short.MAX_VALUE))
        );

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/2.png"))); // NOI18N

        javax.swing.GroupLayout TempP2Layout = new javax.swing.GroupLayout(TempP2);
        TempP2.setLayout(TempP2Layout);
        TempP2Layout.setHorizontalGroup(
            TempP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TempP2Layout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addComponent(jLabel37)
                .addContainerGap(312, Short.MAX_VALUE))
        );
        TempP2Layout.setVerticalGroup(
            TempP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TempP2Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jLabel37)
                .addContainerGap(138, Short.MAX_VALUE))
        );

        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/3.png"))); // NOI18N

        javax.swing.GroupLayout PRecP1Layout = new javax.swing.GroupLayout(PRecP1);
        PRecP1.setLayout(PRecP1Layout);
        PRecP1Layout.setHorizontalGroup(
            PRecP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PRecP1Layout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addComponent(jLabel38)
                .addContainerGap(310, Short.MAX_VALUE))
        );
        PRecP1Layout.setVerticalGroup(
            PRecP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PRecP1Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jLabel38)
                .addContainerGap(138, Short.MAX_VALUE))
        );

        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/4.png"))); // NOI18N

        javax.swing.GroupLayout PrecP2Layout = new javax.swing.GroupLayout(PrecP2);
        PrecP2.setLayout(PrecP2Layout);
        PrecP2Layout.setHorizontalGroup(
            PrecP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PrecP2Layout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addComponent(jLabel39)
                .addContainerGap(313, Short.MAX_VALUE))
        );
        PrecP2Layout.setVerticalGroup(
            PrecP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PrecP2Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jLabel39)
                .addContainerGap(137, Short.MAX_VALUE))
        );

        MainMenu.setText("Climate data");
        MainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MainMenuActionPerformed(evt);
            }
        });

        ExitMenu.setText("Exit");
        ExitMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitMenuActionPerformed(evt);
            }
        });
        MainMenu.add(ExitMenu);

        jMenuBar1.add(MainMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(TempPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(PrecPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ProgressBarTempP1P, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ProgressBarTempP1P2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ProgressBarPrecP1P3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ProgressBarPrecP1P9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(SeasonalTempP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(SeasonalTempP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(444, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SeasonalPrecP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(22, 22, 22)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(42, 42, 42)
                    .addComponent(SeasonalPrecP9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(423, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(TempP1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(TempP2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(PRecP1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(PrecP2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(178, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(TempPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(PrecPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ProgressBarTempP1P, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ProgressBarTempP1P2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ProgressBarPrecP1P3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ProgressBarPrecP1P9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(SeasonalTempP1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(SeasonalTempP2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(30, 30, 30)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(31, 31, 31)
                    .addComponent(SeasonalPrecP1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(20, 20, 20)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(46, 46, 46)
                    .addComponent(SeasonalPrecP9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(47, 47, 47)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(TempP1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(TempP2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(30, 30, 30)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(PRecP1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(30, 30, 30)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(PrecP2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(20, 20, 20)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MainMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MainMenuActionPerformed

    private void ExitMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitMenuActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ExitMenuActionPerformed

    private void PrecipitationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrecipitationActionPerformed
        jPanel2.setVisible(false);
        PrecPanel.setVisible(true);
    }//GEN-LAST:event_PrecipitationActionPerformed

    private void TemperatureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TemperatureActionPerformed
    jPanel2.setVisible(false);
    TempPanel.setVisible(true);

        
    }//GEN-LAST:event_TemperatureActionPerformed

    
    private void PeriodPrecP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PeriodPrecP1ActionPerformed
        TempPanel.setVisible(false);
        ProgressBarTempP1P.setVisible(false);
        jPanel2.setVisible(false);
        PrecPanel.setVisible(false);
        ProgressBarTempP1P2.setVisible(false);
        ProgressBarPrecP1P3.setVisible(true);
        ProgressBarPrecP1P9.setVisible(false);
        ProgressBarTempP1P.setVisible(false);
    }//GEN-LAST:event_PeriodPrecP1ActionPerformed

    private void PrecP2PeriodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrecP2PeriodActionPerformed
        TempPanel.setVisible(false);
        ProgressBarTempP1P.setVisible(false);
        jPanel2.setVisible(false);
        PrecPanel.setVisible(false);
        ProgressBarTempP1P2.setVisible(false);
        ProgressBarPrecP1P3.setVisible(false);
        ProgressBarPrecP1P9.setVisible(true);
        ProgressBarTempP1P.setVisible(false);
    }//GEN-LAST:event_PrecP2PeriodActionPerformed

    private void PrecBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrecBackActionPerformed
        TempPanel.setVisible(false);
        ProgressBarTempP1P.setVisible(false);
        jPanel2.setVisible(true);
        PrecPanel.setVisible(false);
        ProgressBarTempP1P2.setVisible(false);
        ProgressBarPrecP1P3.setVisible(false);
        ProgressBarPrecP1P9.setVisible(false);
        ProgressBarTempP1P.setVisible(false);
    }//GEN-LAST:event_PrecBackActionPerformed

    private void BackFromPBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackFromPBarActionPerformed
        TempPanel.setVisible(false);
        ProgressBarTempP1P.setVisible(false);
        jPanel2.setVisible(true);
        PrecPanel.setVisible(false);
    }//GEN-LAST:event_BackFromPBarActionPerformed

    private void SeasonPrecP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeasonPrecP1ActionPerformed
       SeasonalPrecP1.setVisible(true);    
          PrecPanel.setVisible(false);
    }//GEN-LAST:event_SeasonPrecP1ActionPerformed

    private void SeasonalPrecP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeasonalPrecP2ActionPerformed
        SeasonalPrecP9.setVisible(true);    
         PrecPanel.setVisible(false);
    }//GEN-LAST:event_SeasonalPrecP2ActionPerformed

    private void PeriodTempP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PeriodTempP1ActionPerformed
        TempPanel.setVisible(false);
        ProgressBarTempP1P.setVisible(false);
        jPanel2.setVisible(false);
        PrecPanel.setVisible(false);
        ProgressBarTempP1P2.setVisible(false);
        ProgressBarPrecP1P3.setVisible(false);
        ProgressBarPrecP1P9.setVisible(false);
        ProgressBarTempP1P.setVisible(true);
    }//GEN-LAST:event_PeriodTempP1ActionPerformed

    private void TempP2Period1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TempP2Period1ActionPerformed
        TempPanel.setVisible(false);
        ProgressBarTempP1P.setVisible(false);
        jPanel2.setVisible(false);
        PrecPanel.setVisible(false);
        ProgressBarTempP1P2.setVisible(true);
        ProgressBarPrecP1P3.setVisible(false);
        ProgressBarPrecP1P9.setVisible(false);
        ProgressBarTempP1P.setVisible(false);
    }//GEN-LAST:event_TempP2Period1ActionPerformed

    private void TempBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TempBack1ActionPerformed
        TempPanel.setVisible(false);
        ProgressBarTempP1P.setVisible(false);
        jPanel2.setVisible(true);
        PrecPanel.setVisible(false);
        ProgressBarTempP1P2.setVisible(false);
        ProgressBarPrecP1P3.setVisible(false);
        ProgressBarPrecP1P9.setVisible(false);
        ProgressBarTempP1P.setVisible(false);
        
        
        
    }//GEN-LAST:event_TempBack1ActionPerformed

    private void SeasonTempP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeasonTempP2ActionPerformed
          SeasonalTempP1.setVisible(true);    
          TempPanel.setVisible(false);
        
    }//GEN-LAST:event_SeasonTempP2ActionPerformed

    private void SeasonalPrecP3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeasonalPrecP3ActionPerformed
     SeasonalTempP2.setVisible(true);    
     TempPanel.setVisible(false);
    }//GEN-LAST:event_SeasonalPrecP3ActionPerformed

    private void BackFromPBar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackFromPBar1ActionPerformed
       TempPanel.setVisible(false);
        ProgressBarTempP1P.setVisible(false);
        jPanel2.setVisible(true);
        PrecPanel.setVisible(false);
        ProgressBarTempP1P2.setVisible(false);
        ProgressBarPrecP1P3.setVisible(false);
        ProgressBarPrecP1P9.setVisible(false);
        ProgressBarTempP1P.setVisible(false);
          SeasonalTempP1.setVisible(false);
        SeasonalTempP2.setVisible(false);
        SeasonalPrecP1.setVisible(false);
        SeasonalPrecP9.setVisible(false);
    }//GEN-LAST:event_BackFromPBar1ActionPerformed

    private void BackFromPBar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackFromPBar2ActionPerformed
       TempPanel.setVisible(false);
        ProgressBarTempP1P.setVisible(false);
        jPanel2.setVisible(true);
        PrecPanel.setVisible(false);
        ProgressBarTempP1P2.setVisible(false);
        ProgressBarPrecP1P3.setVisible(false);
        ProgressBarPrecP1P9.setVisible(false);
        ProgressBarTempP1P.setVisible(false);
          SeasonalTempP1.setVisible(false);
        SeasonalTempP2.setVisible(false);
        SeasonalPrecP1.setVisible(false);
        SeasonalPrecP9.setVisible(false);
    }//GEN-LAST:event_BackFromPBar2ActionPerformed

    private void BackFromPBar13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackFromPBar13ActionPerformed
        // TODO add your handling code here:
        TempPanel.setVisible(false);
        ProgressBarTempP1P.setVisible(false);
        jPanel2.setVisible(true);
        PrecPanel.setVisible(false);
        ProgressBarTempP1P2.setVisible(false);
        ProgressBarPrecP1P3.setVisible(false);
        ProgressBarPrecP1P9.setVisible(false);
        ProgressBarTempP1P.setVisible(false);
          SeasonalTempP1.setVisible(false);
        SeasonalTempP2.setVisible(false);
        SeasonalPrecP1.setVisible(false);
        SeasonalPrecP9.setVisible(false);
    }//GEN-LAST:event_BackFromPBar13ActionPerformed

    private void BackFromPBar14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackFromPBar14ActionPerformed
        TempPanel.setVisible(false);
        ProgressBarTempP1P.setVisible(false);
        jPanel2.setVisible(true);
        PrecPanel.setVisible(false);
        ProgressBarTempP1P2.setVisible(false);
        ProgressBarPrecP1P3.setVisible(false);
        ProgressBarPrecP1P9.setVisible(false);
        ProgressBarTempP1P.setVisible(false);
        SeasonalTempP1.setVisible(false);
        SeasonalTempP2.setVisible(false);
        SeasonalPrecP1.setVisible(false);
        SeasonalPrecP9.setVisible(false);
    }//GEN-LAST:event_BackFromPBar14ActionPerformed

    private void BackFromPBar15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackFromPBar15ActionPerformed
        TempPanel.setVisible(false);
        ProgressBarTempP1P.setVisible(false);
        jPanel2.setVisible(true);
        PrecPanel.setVisible(false);
        ProgressBarTempP1P2.setVisible(false);
        ProgressBarPrecP1P3.setVisible(false);
        ProgressBarPrecP1P9.setVisible(false);
        ProgressBarTempP1P.setVisible(false);
        SeasonalTempP1.setVisible(false);
        SeasonalTempP2.setVisible(false);
        SeasonalPrecP1.setVisible(false);
        SeasonalPrecP9.setVisible(false);
// TODO add your handling code here:
    }//GEN-LAST:event_BackFromPBar15ActionPerformed

    private void BackFromPBar19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackFromPBar19ActionPerformed
        // TODO add your handling code here:
        TempPanel.setVisible(false);
        ProgressBarTempP1P.setVisible(false);
        jPanel2.setVisible(true);
        PrecPanel.setVisible(false);
        ProgressBarTempP1P2.setVisible(false);
        ProgressBarPrecP1P3.setVisible(false);
        ProgressBarPrecP1P9.setVisible(false);
        ProgressBarTempP1P.setVisible(false);
        SeasonalTempP1.setVisible(false);
        SeasonalTempP2.setVisible(false);
        SeasonalPrecP1.setVisible(false);
        SeasonalPrecP9.setVisible(false);
    }//GEN-LAST:event_BackFromPBar19ActionPerformed

    private void BackFromPBar20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackFromPBar20ActionPerformed
        TempPanel.setVisible(false);
        ProgressBarTempP1P.setVisible(false);
        jPanel2.setVisible(true);
        PrecPanel.setVisible(false);
        ProgressBarTempP1P2.setVisible(false);
        ProgressBarPrecP1P3.setVisible(false);
        ProgressBarPrecP1P9.setVisible(false);
        ProgressBarTempP1P.setVisible(false);
        SeasonalTempP1.setVisible(false);
        SeasonalTempP2.setVisible(false);
        SeasonalPrecP1.setVisible(false);
        SeasonalPrecP9.setVisible(false);
    }//GEN-LAST:event_BackFromPBar20ActionPerformed

    private void TempAnnualP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TempAnnualP2ActionPerformed
        TempPanel.setVisible(false);
        TempP1.setVisible(true);
    }//GEN-LAST:event_TempAnnualP2ActionPerformed

    private void AnnualPrecP3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnnualPrecP3ActionPerformed
       TempPanel.setVisible(false);
        TempP2.setVisible(true);
    }//GEN-LAST:event_AnnualPrecP3ActionPerformed

    private void precAnnualP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precAnnualP1ActionPerformed
         PrecPanel.setVisible(false);
        PRecP1.setVisible(true);
    }//GEN-LAST:event_precAnnualP1ActionPerformed

    private void AnnualPrecP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnnualPrecP2ActionPerformed

        PrecPanel.setVisible(false);
        PrecP2.setVisible(true);
    }//GEN-LAST:event_AnnualPrecP2ActionPerformed

    
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new  MainFrame().setVisible(true);
            }
        });
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AnnualPrecP2;
    private javax.swing.JButton AnnualPrecP3;
    private javax.swing.JButton BackFromPBar;
    private javax.swing.JButton BackFromPBar1;
    private javax.swing.JButton BackFromPBar10;
    private javax.swing.JButton BackFromPBar11;
    private javax.swing.JButton BackFromPBar12;
    private javax.swing.JButton BackFromPBar13;
    private javax.swing.JButton BackFromPBar14;
    private javax.swing.JButton BackFromPBar15;
    private javax.swing.JButton BackFromPBar16;
    private javax.swing.JButton BackFromPBar17;
    private javax.swing.JButton BackFromPBar18;
    private javax.swing.JButton BackFromPBar19;
    private javax.swing.JButton BackFromPBar2;
    private javax.swing.JButton BackFromPBar20;
    private javax.swing.JButton BackFromPBar3;
    private javax.swing.JButton BackFromPBar4;
    private javax.swing.JButton BackFromPBar5;
    private javax.swing.JButton BackFromPBar6;
    private javax.swing.JButton BackFromPBar7;
    private javax.swing.JButton BackFromPBar8;
    private javax.swing.JButton BackFromPBar9;
    private javax.swing.JMenuItem ExitMenu;
    private javax.swing.JMenu MainMenu;
    private javax.swing.JPanel PRecP1;
    private javax.swing.JButton PeriodPrecP1;
    private javax.swing.JButton PeriodTempP1;
    private javax.swing.JLabel PrePer;
    private javax.swing.JButton PrecBack;
    private javax.swing.JLabel PrecLabelP2;
    private javax.swing.JLabel PrecP1Label;
    private javax.swing.JPanel PrecP2;
    private javax.swing.JButton PrecP2Period;
    private javax.swing.JPanel PrecPanel;
    private javax.swing.JButton Precipitation;
    private javax.swing.JPanel ProgressBarPrecP1P3;
    private javax.swing.JPanel ProgressBarPrecP1P4;
    private javax.swing.JPanel ProgressBarPrecP1P5;
    private javax.swing.JPanel ProgressBarPrecP1P6;
    private javax.swing.JPanel ProgressBarPrecP1P9;
    private javax.swing.JPanel ProgressBarTempP1P;
    private javax.swing.JPanel ProgressBarTempP1P1;
    private javax.swing.JPanel ProgressBarTempP1P2;
    private javax.swing.JPanel ProgressBarTempP1P3;
    private javax.swing.JPanel ProgressBarTempP1P4;
    private javax.swing.JPanel ProgressBarTempP1P5;
    private javax.swing.JPanel ProgressBarTempP1P6;
    private javax.swing.JPanel ProgressBarTempP1P7;
    private javax.swing.JPanel ProgressBarTempP1P8;
    private javax.swing.JButton SeasonPrecP1;
    private javax.swing.JButton SeasonTempP2;
    private javax.swing.JPanel SeasonalPrecP1;
    private javax.swing.JButton SeasonalPrecP2;
    private javax.swing.JButton SeasonalPrecP3;
    private javax.swing.JPanel SeasonalPrecP9;
    private javax.swing.JPanel SeasonalTempP1;
    private javax.swing.JPanel SeasonalTempP2;
    private javax.swing.JPanel SeasonalTempP3;
    private javax.swing.JPanel SeasonalTempP4;
    private javax.swing.JPanel SeasonalTempP6;
    private javax.swing.JPanel SeasonalTempP7;
    private javax.swing.JPanel SeasonalTempP8;
    private javax.swing.JButton TempAnnualP2;
    private javax.swing.JButton TempBack1;
    private javax.swing.JLabel TempLabelP3;
    private javax.swing.JPanel TempP1;
    private javax.swing.JLabel TempP1Label1;
    private javax.swing.JPanel TempP2;
    private javax.swing.JButton TempP2Period1;
    private javax.swing.JPanel TempPanel;
    private javax.swing.JLabel TempPer1;
    private javax.swing.JButton Temperature;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JProgressBar jProgressBar2;
    private javax.swing.JProgressBar jProgressBar3;
    private javax.swing.JButton precAnnualP1;
    // End of variables declaration//GEN-END:variables

    
}
